application/models.py
from flask_login import UserMixin
from flask_bcrypt import Bcrypt
from . import db

bcrypt = Bcrypt()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(160), unique=False, nullable=False)

    # One to many relationship with Cart
    cart = db.relationship('Cart', backref='user')


    # Functions
    def __repr__(self):
        return '<User %r>' % self.username
    
    ''' Functions for user password '''
    @property
    def password(self):
        return self.password_hash
    
    @password.setter
    def set_password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password).decode('utf-8')
    
    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)
    
    ''' Set user.is_admin to False(for navbar) '''
    def is_admin(self):
        return False


class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    
    # One user can have many cart objects each with different product_id
    prod_id = db.Column(db.Integer, db.ForeignKey('product.id'), nullable=False)
    product_quantity = db.Column(db.Integer, nullable=False)


    # Functions
    def __repr__(self):
        return '<Cart %r>' % self.id


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(80), unique=True, nullable=False)
    product_picture = db.Column(db.String(160), nullable=False, default='default.png')
    total_quantity = db.Column(db.Integer, unique=False, nullable=False)
    rate_per_unit = db.Column(db.Integer, unique=False, nullable=False)
    manufacture_date = db.Column(db.Date, unique=False, nullable=False)
    
    # Foreign keys
    unit_id = db.Column(db.Integer, db.ForeignKey('unit.id'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)

    # One to many relationship with Cart
    cart = db.relationship('Cart', backref='product', lazy=True)


    #   Functions
    def __repr__(self):
        return '<Product %r>' % self.product_name


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column(db.String(80), unique=True, nullable=False)
    category_picture = db.Column(db.String(80), nullable=False, default='default.png')
    products = db.relationship('Product', backref='category', lazy=True)


    # Functions
    def __repr__(self):
        return '<Category %r>' % self.category_name


class Admin(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    admin_name = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(160), unique=False, nullable=False)


    # Functions
    def __repr__(self):
        return '<Admin %r>' % self.admin_name
    ''' Functions for admin password '''
    @property
    def password(self):
        return self.password_hash
    
    @password.setter
    def set_password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password).decode('utf-8')
    
    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)
    
    ''' Set user.is_admin to True(for navbar) '''
    def is_admin(self):
        return True


class Unit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    unit_name = db.Column(db.String(80), unique=True, nullable=False)
    products = db.relationship('Product', backref='unit', lazy=True)


    # Functions
    def __repr__(self):
        return '<Unit %r>' % self.unit_name




        

application/__init__.py
from flask import Flask, request, session, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager, current_user


db = SQLAlchemy()
DB_NAME = "database.sqlite3"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "JyHUS*(67679*^&3!$jiJS*Hs" 
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    
    from .views import views
    from .auth_user import auth_user
    from .auth_admin import auth_admin
    from .models import User, Admin, Cart, Product, Category, Unit
    
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth_user, url_prefix="/")
    app.register_blueprint(auth_admin, url_prefix="/admin")
    
    create_database(app)

    login_manager = LoginManager(app)
    login_manager.blueprint_login_views = {'auth_user': 'auth_user.login', 'auth_admin': 'auth_admin.admin_login'}
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        if session.get('user_type') == 'admin':
            x = Admin.query.get(str(id))
        elif session.get('user_type') == 'user':
            x = User.query.get(str(id))
        else:
            x = None  
        return x
    
    return app


def create_database(app):
    from .models import User, Admin, Cart, Product, Category, Unit
    if not path.exists("application/" + DB_NAME):
        with app.app_context():
            db.create_all()
            
        print("Created database!")






application/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import current_user
from .models import User, Category, Product
from . import db
from datetime import datetime

views = Blueprint("views", __name__)


#Home page
@views.route("/")
def home():
    return render_template("home.html", user=current_user, ctgrs=Category.query.all(), products=Product.query.all())


#To search for products
@views.route("/search", methods=['GET', 'POST'])
def search():
    query = request.args.get('query')
    price = request.args.get('price')
    date_filter = request.args.get('date_filter')
    category_id = request.args.get('category_id')

    if not price and not date_filter and not category_id and not query:
        return redirect(url_for('views.home'))

    categories = None
    ctgrs = Category.query.all()
    products = Product.query

    if query:
        categories = Category.query
        categories = categories.filter(Category.category_name.contains(query))
        categories = categories.all()

        products = products.filter(Product.product_name.contains(query))


    if price:
        products = products.filter(Product.rate_per_unit <= float(price))

    if date_filter:
        date_filter = datetime.strptime(date_filter, '%Y-%m-%d').date()
        products = products.filter(Product.manufacture_date >= date_filter)

    if category_id:
        products = products.filter(Product.category_id == category_id)
        
    products = products.all()

    return render_template("search_results.html", user=current_user, ctgrs=ctgrs, categories=categories, products=products, price=price, date_filter=date_filter, category_id=category_id, query=query)


#To view products of a particular category
@views.route("/category/<int:category_id>")
def view_category(category_id):
    category = Category.query.filter_by(id=category_id).first()
    products = Product.query.filter_by(category_id=category.id).all()
    return render_template("category.html", user=current_user, category=category, products=products)


#To view a particular product
@views.route("/product/<int:product_id>")
def view_product(product_id):
    product = Product.query.filter_by(id=product_id).first()
    return render_template("product.html", user=current_user, product=product)


#To view all categories
@views.route("/categories")
def categories():
    return render_template("all_categories.html", user=current_user, ctgrs=Category.query.all())


#To view all products
@views.route("/products")
def products():
    return render_template("all_products.html", user=current_user, products=Product.query.all())



application/templates/all_categories.html
{% extends "base.html" %}

<!-- Title Section -->
{% block title %}QuickGrocer{% endblock %}

<!-- Hero Section -->
{% block hero %} {% include "search_form.html" %} {% endblock %}

<!---->
{% block content %}
<!-- Category List -->
{% if ctgrs %}
<h2 class="navbar text-center bg-info text-white text-monospace">Categories</h2>
<section class="py-5">
    <div class="container">
        <div class="row">
            {% for category in ctgrs %}
            <div class="col-lg-4 mb-4">
                <div class="card">
                    <a
                        href="{{ url_for('views.view_category', category_id=category.id) }}"
                        class="card-img-link">
                        <img
                            class="card-img-top"
                            src="{{ url_for('static', filename='images/' + category.category_picture) }}"
                            alt="category Image" />
                    </a>

                    <div class="card-body align-cat-title">
                        <h4 class="card-title">{{ category.category_name }}</h4>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- Add more category cards here -->
        </div>
    </div>
</section>
{% endif %} {% endblock %}

application/templates/all_products.html
{% extends "base.html" %}

<!-- Title Section -->
{% block title %}QuickGrocer{% endblock %}

<!-- Hero Section -->
{% block hero %} {% include "search_form.html" %} {% endblock %}

<!---->
{% block content %}

<!-- Product List -->
{% include "product_section.html" %} {% endblock %}

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Add Bootstrap CSS link -->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
        <!-- Add custom CSS styles -->
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/style.css') }}" />
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('views.home') }}"
                    >QuickGrocer</a
                >

                <button
                    class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        {% if not user.is_authenticated %}
                        <li class="nav-item active">
                            <a
                                class="nav-link"
                                href="{{ url_for('views.home') }}"
                                >Home</a
                            >
                        </li>
                        {% endif %} {% if user.is_authenticated %}
                        <!-- Check if current_user is admin -->
                        {% if user.is_admin() %}
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.admin_view') }}"
                                >Admin View</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.new_category') }}"
                                >Add Category</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.new_product') }}"
                                >Add Product</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.new_unit') }}"
                                >Add Unit</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.category_list') }}"
                                >Category List</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.product_list') }}"
                                >Product List</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.unit_list') }}"
                                >Unit List</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.admin_logout') }}"
                                style="color: red"
                                >Logout</a
                            >
                        </li>
                        {% else %}
                        <li class="nav-item active">
                            <a
                                class="nav-link"
                                href="{{ url_for('views.home') }}"
                                >Home</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('views.products') }}"
                                >Products</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('views.categories') }}"
                                >Categories</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_user.cart') }}"
                                >Cart</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_user.logout') }}"
                                style="color: red"
                                >Logout</a
                            >
                        </li>
                        {% endif %}
                        <!-- Outer else block -->
                        {% else %}
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_user.login') }}"
                                >Login</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_user.signup') }}"
                                >Signup</a
                            >
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link"
                                href="{{ url_for('auth_admin.admin_login') }}"
                                style="color: red"
                                >!!! Admins Only !!!</a
                            >
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Flash Messages -->
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div
            class="alert alert-danger alter-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div
            class="alert alert-success alter-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

        <!-- Hero Section -->
        {% block hero %}{% endblock %}

        <br />

        <!-- Main Content -->
        <div class="container">{% block content %}{% endblock %}</div>

        <!-- Footer -->
        <br /><br /><br /><br /><br /><br /><br /><br /><br />
        <footer class="bg-dark text-white text-center py-3">
            <p>&copy; 2023 QuickGrocer App. All rights reserved.</p>
        </footer>

        <!-- Add Bootstrap and jQuery JS scripts -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <!-- Custom JS scripts -->
        <script>
            // Add an event listener to the button
            function oldImagePreviewer() {
                // Get references to the old image and the button
                var oldImage = document.getElementById("oldImage");
                var showOldImageButton =
                    document.getElementById("oldImageButton");
                if (oldImage.style.display === "none") {
                    // Show the old image when the button is clicked
                    oldImage.style.display = "block";
                    oldImageButton.value = "Hide Old Image";
                    oldImageButton.className = "btn btn-danger";
                } else {
                    // Hide the old image when the button is clicked again
                    oldImage.style.display = "none";
                    oldImageButton.value = "Show Old Image";
                    oldImageButton.className = "btn btn-info";
                }
            }
        </script>
    </body>
</html>

application/templates/cart.html
{% extends "base.html" %}

<!-- Title Section -->
{% block title %}QuickGrocer Cart{% endblock %}

<!-- Hero Section -->
{% block hero %} {% include "search_form.html" %} {% endblock %}

<!---->

{% block content %}
<div class="row">
    <div class="col">
        <h2>Your Cart</h2>
    </div>
    <div class="col">
        <div class="d-flex justify-content-end align-items-center">
            <a
                href="{{ url_for('auth_user.remove_all_from_cart') }}"
                class="btn btn-outline-danger"
                style="margin-right: 10px"
                >Clear Cart</a
            >
            <a
                href="{{ url_for('auth_user.purchase_all') }}"
                class="btn btn-primary"
                style="margin-left: 10px"
                >Buy All!</a
            >
        </div>
    </div>
</div>

<!-- Cart Section -->
{% if carts %} {% for cart in carts %}
<div class="container">
    <hr />
    <br />
    <div class="row">
        <div class="col">
            <h3 class="mt-4">
                <strong>{{ cart.product.product_name }}</strong>
            </h3>
            <img
                src="{{ url_for('static', filename='images/' + cart.product.product_picture) }}"
                alt="product Image"
                class="img-fluid small-img" />
        </div>
        <div class="col vertical-line">
            <br />
            <h5>
                <strong>Category:</strong>
                {{ cart.product.category.category_name }}
            </h5>
            <h5>
                <strong>Price Per Unit:</strong> ₹{{ cart.product.rate_per_unit
                }}/{{ cart.product.unit.unit_name }}
            </h5>
            <h5>
                <strong>Manufacture Date:</strong> {{
                cart.product.manufacture_date }}
            </h5>
            <h5><strong>Quantity:</strong> {{ cart.product_quantity }}</h5>
            <h5>
                <strong>Total Price</strong> ₹{{ cart.product.rate_per_unit *
                cart.product_quantity }}
            </h5>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <br />
            <div class="d-flex justify-content-center align-carts-center">
                <a
                    href="{{ url_for('auth_user.update_cart', cart_id=cart.id) }}"
                    class="btn btn-outline-primary"
                    style="margin-right: 10px"
                    >Edit Cart</a
                >
                <a
                    href="{{ url_for('auth_user.remove_from_cart', cart_id=cart.id) }}"
                    class="btn btn-outline-primary"
                    style="margin-left: 10px; margin-right: 10px"
                    >Remove from Cart</a
                >
                <a
                    href="{{ url_for('auth_user.purchase_cart', cart_id=cart.id) }}"
                    class="btn btn-primary"
                    style="margin-left: 10px"
                    >Buy Now!</a
                >
            </div>
        </div>
    </div>
    <br />
</div>
{% endfor %} {% else %}
<br />
<hr />
<br />
<h4>
    <span class="text-danger">Your Cart is Empty</span>
</h4>
{% endif %} {% endblock %}

application/templates/home.html
{% extends "base.html" %}

<!-- Title Section -->
{% block title %}QuickGrocer{% endblock %}

<!-- Hero Section -->
{% block hero %}
<!---->
{% include "search_form.html" %}
<section class="jumbotron text-center bg-primary text-white">
    <div class="container">
        <h1>Welcome to QuickGrocer</h1>
        <p class="lead">
            Browse our wide range of fresh groceries at the best prices!
        </p>
        <a href="#home" class="btn btn-light btn-lg">Shop Now</a>
    </div>
</section>
{% endblock %}

<!-- Product List Section -->
{% block content %}

<div id="home"></div>

<!-- Category List -->
{% if ctgrs %}
<h2 class="navbar text-center bg-info text-white text-monospace">Categories</h2>
<section class="py-5">
    <div class="container">
        <div class="row">
            {% for category in ctgrs %}
            <div class="col-lg-4 mb-4">
                <div class="card">
                    <a
                        href="{{ url_for('views.view_category', category_id=category.id) }}"
                        class="card-img-link">
                        <img
                            class="card-img-top"
                            src="{{ url_for('static', filename='images/' + category.category_picture) }}"
                            alt="category Image" />
                    </a>

                    <div class="card-body align-cat-title">
                        <h4 class="card-title">{{ category.category_name }}</h4>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endif %}

<!-- Product List -->
{% include "product_section.html" %} {% endblock %}

application/templates/product_section.html
<!-- Product List Section -->
{% if products %}
<h2 class="navbar text-center bg-info text-white text-monospace">Products</h2>
<section class="py-5">
    <div class="container">
        <div class="row">
            {% for product in products %}
            <div class="col-lg-4 mb-4">
                <div class="card">
                    <a
                        href="{{ url_for('views.view_product', product_id=product.id) }}"
                        class="card-img-link">
                        <img
                            class="card-img-top"
                            src="{{ url_for('static', filename='images/' + product.product_picture) }}"
                            alt="Product Image" />
                    </a>

                    <div class="card-body">
                        <h5 class="card-title">{{ product.product_name }}</h5>
                        <p class="card-text">
                            ₹{{ product.rate_per_unit }}/{{
                            product.unit.unit_name }}
                        </p>
                        <div
                            class="d-flex justify-content-center align-items-center">
                            <a
                                href="{{ url_for('auth_user.add_to_cart', product_id=product.id) }}"
                                class="btn btn-outline-primary"
                                style="margin-right: 10px"
                                >Add to Cart</a
                            >
                            <a
                                href="{{ url_for('auth_user.purchase_product', product_id=product.id) }}"
                                class="btn btn-primary"
                                style="margin-left: 10px"
                                >Buy Now!</a
                            >
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endif %}

application/templates/search_results.html
{% extends 'base.html' %}

<!-- Title Section -->
{% block title %}QuickGrocer{% endblock %}

<!-- Hero Section -->
{% block hero %} {% include "search_form.html" %} {% endblock %}

<!-- Search Results -->

{% block content %}

<div class="container">
    {% if query %}
    <h4>Search Results for "{{ query }}"</h4>
    {% endif %}

    <!-- Display no results if no categories or products -->
    {% if not categories and not products %}
    <h4>No results found</h4>
    {% else %}

    <hr />

    <!-- Search Results Section -->
    <!-- Category List -->
    {% if categories %}
    <h2 class="navbar text-center bg-info text-white text-monospace">
        Categories
    </h2>
    <section class="py-5">
        <div class="container">
            <div class="row">
                {% for category in categories %}
                <div class="col-lg-4 mb-4">
                    <div class="card">
                        <a
                            href="{{ url_for('views.view_category', category_id=category.id) }}"
                            class="card-img-link">
                            <img
                                class="card-img-top"
                                src="{{ url_for('static', filename='images/' + category.category_picture) }}"
                                alt="category Image" />
                        </a>

                        <div class="card-body align-cat-title">
                            <h4 class="card-title">
                                {{ category.category_name }}
                            </h4>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- Add more category cards here -->
            </div>
        </div>
    </section>
    {% endif %}

    <!-- Product List -->
    {% include "product_section.html" %} {% endif %}
</div>
{% endblock %}

application/templates/update_cart.html
{% extends "base.html" %}

<!-- Title Section -->
{% block title %}QuickGrocer{% endblock %}

<!-- Hero Section -->
{% block hero %} {% include "search_form.html" %} {% endblock %}

<!---->

{% block content %} {% if cart %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mt-4">Confirm updating the cart :</h1>
            <hr />
            <h3 class="mt-4">
                <strong>{{ cart.product.product_name }}</strong>
            </h3>
            <h3 class="mt-4">
                <img
                    src="{{ url_for('static', filename='images/' + cart.product.product_picture) }}"
                    alt="Image of {{ cart.product.product_name }}" />
            </h3>
            <hr />
            <form
                method="post"
                action="{{ url_for('auth_user.update_cart', cart_id=cart.id) }}"
                enctype="multipart/form-data">
                <br />
                <div class="form-group">
                    <label for="quantity">Quantity:</label>
                    <select name="quantity" id="quantity">
                        {% for i in range(1, 11) %}
                        <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                <br />
                <button type="submit" class="btn btn-primary btn-block">
                    Add to Cart
                </button>
            </form>
            <br />
            <div class="mx-auto" style="width: 60px">
                <a
                    href="{{ url_for('views.view_product', product_id=cart.product.id) }}"
                    class="btn btn-light"
                    >Cancel</a
                >
            </div>
        </div>
    </div>
</div>
{% endif %} {% endblock %}